#!/usr/bin/env php
<?php


require_once "vendor/autoload.php";

use extSkel\{extSkel,FunctionsAnalyzer};

$skel = new extSkel(new FunctionsAnalyzer());

try {
    $skel->checkSapi();

    $options = $skel->getOptions();

    $skel->run($options);

} catch (\Exception $e) {
    echo $e->getMessage();
}



exit;
